[2025-10-18T13:54:54.467+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-18T13:54:54.511+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wiki_trending_pipeline.clean_top_pages manual__2025-10-18T13:41:58.972629+00:00 [queued]>
[2025-10-18T13:54:54.524+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wiki_trending_pipeline.clean_top_pages manual__2025-10-18T13:41:58.972629+00:00 [queued]>
[2025-10-18T13:54:54.524+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 3
[2025-10-18T13:54:54.540+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): clean_top_pages> on 2025-10-18 13:41:58.972629+00:00
[2025-10-18T13:54:54.550+0000] {standard_task_runner.py:63} INFO - Started process 1192 to run task
[2025-10-18T13:54:54.555+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wiki_trending_pipeline', 'clean_top_pages', 'manual__2025-10-18T13:41:58.972629+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/wiki_dag/wiki_top_pages_dag.py', '--cfg-path', '/tmp/tmp5q53llv9']
[2025-10-18T13:54:54.560+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask clean_top_pages
[2025-10-18T13:54:54.644+0000] {task_command.py:426} INFO - Running <TaskInstance: wiki_trending_pipeline.clean_top_pages manual__2025-10-18T13:41:58.972629+00:00 [running]> on host b7a334fdcbb7
[2025-10-18T13:54:54.821+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wiki_trending_pipeline' AIRFLOW_CTX_TASK_ID='clean_top_pages' AIRFLOW_CTX_EXECUTION_DATE='2025-10-18T13:41:58.972629+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-18T13:41:58.972629+00:00'
[2025-10-18T13:54:54.822+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-18T13:54:55.195+0000] {logging_mixin.py:188} INFO - ðŸ“Š Processing file: top_pages_2025_10_17.json
[2025-10-18T13:54:55.345+0000] {logging_mixin.py:188} INFO - âœ“ Bucket 'silver' exists
[2025-10-18T13:55:59.215+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2025-10-18T13:55:59.221+0000] {process_utils.py:132} INFO - Sending 15 to group 1192. PIDs of all processes in the group: [1193, 1192]
[2025-10-18T13:55:59.222+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1192
[2025-10-18T13:55:59.234+0000] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-10-18T13:55:59.235+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-18T13:55:59.271+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/wiki_dag/wiki_top_pages_dag.py", line 162, in clean_top_pages
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/opt/spark/python/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark/python/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/opt/spark/python/pyspark/context.py", line 203, in __init__
    self._do_init(
  File "/opt/spark/python/pyspark/context.py", line 296, in _do_init
    self._jsc = jsc or self._initialize_context(self._conf._jconf)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark/python/pyspark/context.py", line 421, in _initialize_context
    return self._jvm.JavaSparkContext(jconf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1586, in __call__
    answer = self._gateway_client.send_command(command)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2609, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-10-18T13:55:59.283+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=wiki_trending_pipeline, task_id=clean_top_pages, execution_date=20251018T134158, start_date=20251018T135454, end_date=20251018T135559
[2025-10-18T13:55:59.637+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1192, status='terminated', exitcode=2, started='13:54:53') (1192) terminated with exit code 2
[2025-10-18T13:55:59.971+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1193, status='terminated', started='13:54:54') (1193) terminated with exit code None
[2025-10-18T13:55:59.973+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 143
[2025-10-18T13:56:00.012+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-18T13:56:00.384+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
