[2025-10-18T09:49:55.620+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-18T09:49:55.694+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wiki_trending_pipeline.upload_bronze manual__2025-10-18T09:49:51.845181+00:00 [queued]>
[2025-10-18T09:49:55.707+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wiki_trending_pipeline.upload_bronze manual__2025-10-18T09:49:51.845181+00:00 [queued]>
[2025-10-18T09:49:55.708+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-10-18T09:49:55.727+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): upload_bronze> on 2025-10-18 09:49:51.845181+00:00
[2025-10-18T09:49:55.750+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=197) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-18T09:49:55.748+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wiki_trending_pipeline', 'upload_bronze', 'manual__2025-10-18T09:49:51.845181+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/wiki_dag/wiki_top_pages_dag.py', '--cfg-path', '/tmp/tmp410rizuq']
[2025-10-18T09:49:55.752+0000] {standard_task_runner.py:63} INFO - Started process 198 to run task
[2025-10-18T09:49:55.752+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask upload_bronze
[2025-10-18T09:49:55.793+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-18T09:49:55.870+0000] {task_command.py:426} INFO - Running <TaskInstance: wiki_trending_pipeline.upload_bronze manual__2025-10-18T09:49:51.845181+00:00 [running]> on host 6ab8c125868b
[2025-10-18T09:49:56.062+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wiki_trending_pipeline' AIRFLOW_CTX_TASK_ID='upload_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-10-18T09:49:51.845181+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-18T09:49:51.845181+00:00'
[2025-10-18T09:49:56.063+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-18T09:49:56.136+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-18T09:49:56.137+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/upload_to_minio.py", line 20, in upload_to_minio
    file_name = os.path.basename(file_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 171, in basename
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2025-10-18T09:49:56.154+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=wiki_trending_pipeline, task_id=upload_bronze, execution_date=20251018T094951, start_date=20251018T094955, end_date=20251018T094956
[2025-10-18T09:49:56.171+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task upload_bronze (expected str, bytes or os.PathLike object, not NoneType; 198)
[2025-10-18T09:49:56.209+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-18T09:49:56.267+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-18T09:49:56.269+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
